server:
  port: 10000
# 配置服务的名称
spring:  application:    name: eureka10000
eureka:
  instance:    hostname: localhost  client:
       # 注册中心的地址
    service-url:      defaultZone: http://www.bb.com:10001/eureka,http://www.cc.com:10002/eureka
       # 当前服务不能去调用其他服务
    fetch-registry: false
       # 注册中心自我注册    register-with-eureka: false