server:
  port: 40000
eureka:
  client:
    service-url:
      defaultZone: http://www.aa.com:10000/eureka,http://www.bb.com:10001/eureka,http://www.cc.com:10002/eureka
    register-with-eureka: true
spring:
  applicaiton:
    name: gateway
  cloud:
    gateway:
      # 配置gateway的路由功能
      routes:
        # 路由feign
        - id: consumer-feign
          uri: lb://COMSUMER-FEIGN
          # 如何判断当前请求是要访问feign的
          predicates:
            - Path=/a/**
          # 过滤路径的第一个(a),若不过滤会直接把/a/**作为请求进行转发,会出现404错误
          filters:
            - StripPrefix=1
        # 路由ribbon
        - id: consumer-ribbon
          uri: lb://COMSUMER-RIBBON
          predicates:
            - Path=/b/**
          filters:
            - StripPrefix=1