server:
  port: 10001
# 配置服务的名称
spring:
  application:
    name: eureka10001
eureka:
  instance:
    hostname: localhost
  client:
       # 注册中心的地址
    service-url:
      defaultZone: http://www.aa.com:10000/eureka,http://www.cc.com:10002/eureka
       # 当前服务不能去调用其他服务
    fetch-registry: false
       # 注册中心自我注册
    register-with-eureka: false