server:
  port: 30000
spring:  application:    name: comsumer-ribbon
eureka:  client:    service-url:      defaultZone: http://www.aa.com:10000/eureka,http://www.bb.com:10001/eureka,http://www.cc.com:10002/eureka
    register-with-eureka: true